### ISSUE TITLE
Please change the project discription

### ISSUE THREAD

**Issue by Marcel-Baumgartner** [Rabergsel/Fireportal#1]
Hey hey, nice to see a new fork of moonlight ^^
I just want to mention that it is not "Another cool Pterodactyl Panel". As pterodactyl and moonlight are completely different. The only mention able similarity is the use wings from both panels. So please dont insult my software as being the same as pterodactyl :3

**Comment by Rabergsel** [comment]
Hi Marcel,
sorry, this was a misconception on my side :D

I will change that immediatly.
Nice to hear from you.

Regards,
Raphael

**Comment by Marcel-Baumgartner** [comment]
thx <3 

masu :3
